language:        node_js
sudo:            false
cache:
  apt:           true
  directories:
  - node_modules
node_js:
- '8'
branches:
  only:
  - hexo-shutto-trans-product
before_install:
- npm install -g hexo
- npm install
- npm install hexo-renderer-ejs
- npm install hexo-renderer-marked
- npm install hexo-renderer-stylus
before_script:
- git config --global user.name 'hrix via Travis CI'
- git config --global user.email 'hirai.sumito@gmail.com'
- rm -rf public
- git clone --depth=1 --branch=master https://github.com/hrix/hrix.github.io.git public
- pushd public
- git ls-files | xargs -I {} rm -rf {}
- popd
script:
- mv --force misc/themes/casper/layout/casper/head.ejs themes/casper/layout/casper/head.ejs
- hexo generate
- cd public
- git add -A
- git commit -m 'Update'
- '[ "$TRAVIS_BRANCH" == "hexo-shutto-trans-product" ]'
- '[ $GH_TOKEN ]'
- 'git push --force https://$GH_TOKEN@github.com/hrix/hrix.github.io.git HEAD:master'
env:
  global:
  - GIT_COMMITTER_NAME=hrix-via-TravisCI
  - GIT_COMMITTER_EMAIL=hirai.sumito@gmail.com
  - GIT_AUTHOR_NAME=hrix-via-TravisCI
  - GIT_AUTHOR_EMAIL=hirai.sumito@gmail.com
