language: node_js
sudo: false
cache:
  apt: true
  directories:
  - node_modules
node_js:
- '8'
before_install:
- npm uninstall hexo
- npm install -g hexo-cli
- npm install hexo --save
before_script:
- rm -rf public
script:
- hexo generate
- cd public
  
