language: node_js
sudo: false
cache:
  apt: true
  directories:
  - node_modules
node_js:
- '8'
before_install:
- npm install -g hexo
- npm install
before_script:
- rm -rf public
script:
- hexo generate
- cd public
  
