language: node_js

sudo: false

cache:
  apt: true
  directories:
    - node_modules

node_js:
  - "8"
  - "node"

install:
- npm install -g hexo
- npm install -g hexo-cli
- npm install

script: npm run build

after_script:
  - hexo generate

dist: precise
