# config
cover: //blog.ghost.org/content/images/2013/Nov/cover.png
logo: //pbs.twimg.com/profile_images/341135326/S1100.png
bio: 'An infrastructure engineer of inetrnet. https://twitter.com/moro40'

# Content
excerpt_link: Read More

# Miscellaneous
rss:
google_analytics: UA-1865444-17
