# config
cover: //blog.ghost.org/content/images/2013/Nov/cover.png
logo: //lh5.googleusercontent.com/-s9MYEz6KNkA/VGQZhqx63xI/AAAAAAAAAAQ/8Mf0TlYPq9E/s46-c-k-no/S1100_400x400.png
bio: 'An infrastructure engineer of inetrnet'

# Content
excerpt_link: Read More

# Miscellaneous
rss:
google_analytics: UA-1865444-17
