# config
cover: //blog.ghost.org/content/images/2013/Nov/cover.png
logo: //blog.ghost.org/content/images/2013/Nov/bloglogo_1-1.png
bio: 'An infrastructure engineer of inetrnet'

# Content
excerpt_link: Read More

# Miscellaneous
rss:
google_analytics: UA-1865444-17
